### ISSUE TITLE
More information for the exception

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/logger#10]
Currently implementation only shows the reason of the cause. But It should show more information regarding to the issue. Stacktrace can be printed in a propery way.

**Comment by androchentw** [comment]
Hi orhanobut,
I love this repo pretty much! And I'm thinking of the same thing here.
It would be great if I could just `Logger.e(exception);` to simply get all the stacktrace.

Guess this solution should be sufficient: [How can I convert a stack trace to a string?](http://stackoverflow.com/questions/1149703/how-can-i-convert-a-stack-trace-to-a-string)

Thanks!

**Comment by orhanobut** [comment]
@androchentw I know very super late reply but this issue should be fixed now.

**Comment by mateusgrb** [comment]
@orhanobut I'm trying 2.1.1 and 2.2.0 but I don't see any stack trace printed, just the exception name. Example:
![Screen Shot 2019-05-08 at 11 23 34](https://user-images.githubusercontent.com/1141910/57382892-2a407580-7184-11e9-9cd2-c1cf88bbbce0.png)
