### ISSUE TITLE
我能把这个仓库上传到jitpack么

### ISSUE THREAD

**Issue by yizeliang** [orhanobut/logger#101]
你好,我看你好久没有更新了,我能将这个库修改后打包上传jitpack么,方便以后使用

**Comment by YuZhiLiang** [comment]
哪一个仓库? AppleTree吗 发自网易邮箱大师 在2016年12月18日 00:04 ，yizeliang写道： 你好,我看你好久没有更新了,我能将这个库打包上传jitpack么,方便以后使用,当然,如果可以,我还是希望作者本人上传的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yizeliang** [comment]
Logger 仓库,控制台打印仓库,还以为 你是外国人呢=.=

**Comment by yizeliang** [comment]
还以为你看不懂中文...

**Comment by yizeliang** [comment]
@YuZhiLiang Logger库

**Comment by YuZhiLiang** [comment]
肯定是你搞错了 我并没有Logger的库 我在Github上只有一个ApperTree的仓库 发自网易邮箱大师 在2016年12月18日 00:29 ，yizeliang写道： 还以为你看不懂中文... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by van048** [comment]
这。。。是不是搞错了什么。。。

**Comment by YuZhiLiang** [comment]
肯定搞错了🤔 发自网易邮箱大师 在2016年12月18日 10:58 ，BenYang写道： 这。。。是不是搞错了什么。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by orhanobut** [comment]
That'd been great if the conversation was English :) Closing the issue.
