### ISSUE TITLE
AndroidLogAdapter is not public

### ISSUE THREAD

**Issue by pengfeigao** [orhanobut/logger#102]
com.orhanobut.logger.AndroidLogAdapter' is not public in 'com.orhanobut.logger'. Cannot be accessed from outside packag
![qq 20161223172642](https://cloud.githubusercontent.com/assets/9261499/21450798/fdd66f8a-c934-11e6-9618-e8e2599911f4.png)

**Comment by ddxxll2008** [comment]
i couldn't use AndroidLogAdapter too, there is an error.

**Comment by ddxxll2008** [comment]
i couldn't use AndroidLogAdapter too, there is an error.

**Comment by orhanobut** [comment]
The default implementation is AndroidLogAdapter if you don't set, that's why I didn't open it to public.

**Comment by van048** [comment]
Maybe @orhanobut could modify README to prevent misunderstanding.

**Comment by orhanobut** [comment]
There was a big misunderstanding about this. LogAdapter functionality is changed and now all adapters are public.  Please check the new release changes. https://github.com/orhanobut/logger/releases/tag/2.0.0
