### ISSUE TITLE
Options to have an instance of the logger

### ISSUE THREAD

**Issue by budius** [orhanobut/logger#103]
Current logger is completely `static` and impossible to get a reference of Logger or Printer.

This works fine for `apps` but developers doing a library could have issues with values being logged with wrong tags or log_level.

For that would be useful to be able to do something like:

```Java
Logger instance = Logger.init("my tag")
                        .methodCount( ...
                        .logLevel( ...
                        .build();
```

**Comment by tuanchauict** [comment]
@budius Please take a look at my folk : https://github.com/tuanchauict/logger

**Comment by budius** [comment]
@tuanchauict your fork looks pretty nice.

But at the moment we're using jitpack from our branch https://github.com/sensorberg-dev/logger/tree/feature/logger_instance but soon we'll just copy over the parts we want of the logger code and stop using a library all together.

Trying to keep our library with minimum dependencies as possible.

**Comment by orhanobut** [comment]
@budius Clearly good reason to have different instances with different configurations. I changed the log adapter approach in order to make it more cohesive, flexible and to provide multiple log adapters with 2.0.0.
