### ISSUE TITLE
A switcher to close logger

### ISSUE THREAD

**Issue by zhuhoudan** [orhanobut/logger#105]
Can you provide an initialization method to control the log switch, because the project needs to log in test environment, but the production environment needs to close the log.

**Comment by PromiseNev** [comment]
Logger
  .init(YOUR_TAG)                 // default PRETTYLOGGER or use just init()           
  .logLevel(LogLevel.NONE)        // default LogLevel.FULL
}
Best place would be in application class. you can use LogLevel.NONE for the release versions.

**Comment by zhuhoudan** [comment]
Thanks

**Comment by tuanchauict** [comment]
@zhuhoudan Please take a look in my folk. You may find something interesting.

**Comment by orhanobut** [comment]
LogLevel is removed with new version (2.0). In order to disable logs for any condition, you need to override `isLoggable` method now. This will give a lot of flexibility to decide which logs you want to keep etc.
```java
Logger.addLogAdapter(new AndroidLogAdapter(){
  @Override public boolean isLoggable(int priority, String tag) {
    return BuildConfig.DEBUG;
  }
});
```
