### ISSUE TITLE
Feature request: set log level to warn/ warning

### ISSUE THREAD

**Issue by ericn37** [orhanobut/logger#106]
At the moment it's all or nothing.

However, it would really help troubleshooting if I can still allow warning or error log messages in my release app.

**Comment by orhanobut** [comment]
@ericn37 
LogLevel is removed with new version (2.0). In order to disable logs for any condition, you need to override `isLoggable` method now. This will give a lot of flexibility to decide which logs you want to keep etc.
```java
Logger.addLogAdapter(new AndroidLogAdapter(){
  @Override public boolean isLoggable(int priority, String tag) {
    return BuildConfig.DEBUG;
  }
});
```
