### ISSUE TITLE
Version 1.8  do not support Logger.d(TAG, message) ?

### ISSUE THREAD

**Issue by DorisGM** [orhanobut/logger#109]
When I use Logger.d(TAG, message) on Version 1.8, It's unuserful . Logger  only print TAG and no message. But Version 1.3 can support Logger.d(TAG, message)  which can print message and tag. But logger 1.3 have bugs.

**Comment by LiHexiang** [comment]
I have the same problem

**Comment by orhanobut** [comment]
Logger doesn't support this format. First parameter is for message and the second is for string arguments. 

Method signature
```java
Logger.d(String message, Object... args)
```

Usage
```java
Logger.d("message %s", "sent")
```

If you want to use one-time only tag, you can use `t` or if you want to set a custom tag for everything you need to set it via formatstrategy. There is documentation about this in readme file.

One time only tag
```java
Logger.t("tag").d("message")
```

**Comment by mengxilan** [comment]
ovverride createMessage in LoggerPrinter like this: 
//        return args == null || args.length == 0 ? message : String.format(message, args);
        if (args == null || args.length == 0) {
            return message;
        }
        String pattern = "(%\\d)?\\$(a|b|c|d|e|f|g|h|n|s|tx)";
        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(message);
        if (m.find()) {
            return String.format(message, args);
        } else {
            t(message);
            return String.valueOf(args[0]);
        }
