### ISSUE TITLE
Suggestion: Handle Varargs in message 

### ISSUE THREAD

**Issue by kokaz** [orhanobut/logger#11]
Hi,

I want to suggest a feature I would like before I completely agree on migrating to `Logger`. I think you could implement varargs feature in message string. For example, in Timber, I used to do something like that:
```java
Timber.d("Data: %d %d %d %d %s", left, right, top, bottom, input);
```

**Comment by orhanobut** [comment]
I'll check it out and try to find a good solution for this. I may need to change the method signature and add a different style. Apparently this feature is really nice.

**Comment by orhanobut** [comment]
This is added in v1.5

**Comment by kokaz** [comment]
Thanks, officially migrating ;) :+1:
