### ISSUE TITLE
How to save logger to file

### ISSUE THREAD

**Issue by liunewshine** [orhanobut/logger#120]
I want to save Exception to file

**Comment by liunewshine** [comment]
I want to save Exception to file

**Comment by orhanobut** [comment]
There is a new development for persistent logs. You can now use DiskLogAdapter. Each Log adapter also contains a logic for log levels. If you only want to log errors, put a logic something like below.
```java
Logger.addLogAdapter(new DiskLogAdapter(){
  @Override public boolean isLoggable(int priority, String tag) {
     return priority == Logger.ERROR;
  }
})
```
