### ISSUE TITLE
Logger.d(null)

### ISSUE THREAD

**Issue by Sydney-o9** [orhanobut/logger#121]
Would it be able to support debugging for nullable variables?

`Logger.d(my_nullable_variable)`

Typical example would be when you use a HashMap and when trying to get a particular entry, if it doesn't exist, it will return null. 

`Logger.d(entry_in_the_hash_map`) will crash if the entry is not found.

**Comment by orhanobut** [comment]
@Sydney-o9 That makes completely sense. I'll add this check in the next version. 2.1.0

**Comment by orhanobut** [comment]
Fixed with version 2.1.0

**Comment by Sydney-o9** [comment]
Awesome!
