### ISSUE TITLE
Version 2.1.0 not found on maven

### ISSUE THREAD

**Issue by ericn37** [orhanobut/logger#127]
The latest there is 2.0.0
![screen shot 2017-05-29 at 9 49 37 am](https://cloud.githubusercontent.com/assets/19919208/26534192/2ceebc74-4454-11e7-8b0a-977342fa4d3f.png)

**Comment by orhanobut** [comment]
I uploaded the artifacts again. Not sure what happened on maven side with the previous upload. I'll update this issue once it's ready. Thanks for reporting

**Comment by orhanobut** [comment]
It's available now. Can you check it please? Although it'll take a few hours to be visible on maven search but it's available through gradle install.

**Comment by ericn37** [comment]
works now, thank you, sir 👍
