### ISSUE TITLE
Logger doesn't log in multiprocess app

### ISSUE THREAD

**Issue by lgtout** [orhanobut/logger#128]
Hi,

Perhaps it's me not doing something right, but I can't seem to be able to get the logger to print output in a background process of a multiprocess Android app.  

Is the logger designed to operate in multiprocess scenarios?

I have an Android app that has an IntentService that runs in a separate process from the app.  What I've found is that the logger will not print messages to the logcat window for that process.  However, for reference, `android.util.Log` does so.

I prefer using this logger to the android Log, so any suggestions that would allow me to do so would be much appreciated. 

Thanks!

**Comment by orhanobut** [comment]
@lgtout I will check it out. Could it be that it's not initiated? Where do you initiate Logger?

**Comment by orhanobut** [comment]
Closing this issue due to timeout.

**Comment by lgtout** [comment]
I'm sorry I didn't respond sooner.  You were right - I wasn't reinitializing the Logger in the code that runs in each process.  Thanks!
