### ISSUE TITLE
Accept nullable values

### ISSUE THREAD

**Issue by Sydney-o9** [orhanobut/logger#129]
A Long can be `null`:

````java
Long createdAt = null;
Logger.d(createdAt);
````
![screen shot 2017-06-06 at 5 28 28 pm](https://cloud.githubusercontent.com/assets/1480617/26818342/99f8b1a0-4add-11e7-95e7-ae029e77b1d3.png)

Previous work on nullable debug values is in #121.

**Comment by orhanobut** [comment]
Which version are you using?

**Comment by Sydney-o9** [comment]
Thank you @orhanobut for looking into this - I am using the latest.

````
compile 'com.orhanobut:logger:2.1.0'
````

**Comment by orhanobut** [comment]
Released a hotfix for this. Can you try with the new version? 2.1.1

**Comment by Sydney-o9** [comment]
This is great @orhanobut - looks perfect!

````
        Long createdAt = null;
        Logger.d(createdAt); // now prints null
````
