### ISSUE TITLE
Damn thank you!!!!

### ISSUE THREAD

**Issue by sirvon** [orhanobut/logger#13]
thank you for this lib!

this makes logcat 1000000x better.

is there anyway I can get this same look and feel remotely?

thanks man!

**Comment by orhanobut** [comment]
@sirvon thanks! To be honest I didn't exactly get what you meant by remotely. As long as you have logcat, you will have the same look and feel I assume. I haven't tried it in any other environments yet really.

**Comment by sirvon** [comment]
i meant like remote logcat/logging...but you said the words you gotta have logcat for it to look like this. no worries this library brings clarity so its 100000% on point. thank you! indeed.
