### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by yishangfei** [orhanobut/logger#137]
I use   compile 'com.orhanobut:logger:1.15'  Can print

I use   compile 'com.orhanobut:logger:2.1.1'  Can‘t print

why?  Seek answers   thk~

**Comment by quert999** [comment]
@yishangfei  How did you initialize Logger?

**Comment by yishangfei** [comment]
1.15 no need initalize~      2.11 how is  initialize？ @quert999

**Comment by yishangfei** [comment]
README.md  There is to say  initialize？

**Comment by quert999** [comment]
yes, you should read it.

**Comment by orhanobut** [comment]
You need to initialize with `LogAdapter` in order to use it. 
```
Logger.addLogAdapter(new AndroidLogAdapter()); 
```
