### ISSUE TITLE
write log to a file

### ISSUE THREAD

**Issue by hamzux** [orhanobut/logger#14]
Hi thanks very much for this library. 

is it possible to write all log to a file along with the standard output?

Thanks

**Comment by orhanobut** [comment]
Writing all logs to a file could be tricky and costy since permission might be needed especially if the file must be written to external place. But I'll check if there can be any work around or something different.

**Comment by cikichen** [comment]
+1，write log to sdcard.

**Comment by zourb** [comment]
+1，write logs to sdcard.

**Comment by zhouzhiqiangzzq** [comment]
+1，write logs to sdcard.

**Comment by js2892** [comment]
+1

**Comment by leixinstar** [comment]
+1

**Comment by GISirFive** [comment]
+1

**Comment by WasimMemon** [comment]
+1 for feature
Logback library does the same. it will create file for you but requesting permission is totally depend on developer. Before initializing you have to check for permission. you can take reference and add into this library. hope this will help.

**Comment by Mr4Mike4** [comment]
+1

**Comment by tianshan20081** [comment]
+1

**Comment by liudasheng** [comment]
+1

**Comment by tangchao0106** [comment]
+1

**Comment by webpau** [comment]
+1

**Comment by wangzhiyuan** [comment]
+1

**Comment by LessTalk** [comment]
+1

**Comment by Zhongjoe** [comment]
+1

**Comment by orhanobut** [comment]
DiskLogAdapter is in place. Thanks to @budius contribution. Please check README file about how to use it. Since with 2.0 usage is changed.

**Comment by iad24** [comment]
DiskLogAdapter always create log files in CSV format? How bout log it to file the way its displayed in the logcat? like showing the method name, etc
