### ISSUE TITLE
Color coding per Log type

### ISSUE THREAD

**Issue by seljabali** [orhanobut/logger#140]
Hi @orhanobut, 

I just tried out logger & it looks great! In glancing at the [README](https://github.com/orhanobut/logger/blob/master/README.md) for the project for the first time, I assumed one could assign different colors to different log types. That said, is that possible? If so, how?

Thanks,
-Sami

**Comment by orhanobut** [comment]
You can change your Android Studio settings to give different colors for Logcat. Here is a [link](https://stackoverflow.com/questions/39993867/android-studio-logcat-colors-best-practice/39993868) that shows how to do it. 

Cheers,
