### ISSUE TITLE
Number and size of log files

### ISSUE THREAD

**Issue by deeplyloving** [orhanobut/logger#142]
I think the number and size of the log files can provide settings，more than maximum number automatically deleted.
DiskLogStrategy like log4j or logback .......

**Comment by orhanobut** [comment]
Could you elaborate this a little more please? That'd be great if you can give me some example. We can definitely provide more customizable API if needed.

**Comment by orhanobut** [comment]
Closing this issue for now, we can reopen this if there is a need definitely.
