### ISSUE TITLE
Messages are printed twice in the log

### ISSUE THREAD

**Issue by manniakk** [orhanobut/logger#144]
I have setup the logger this way
`FormatStrategy formatStrategy = PrettyFormatStrategy.newBuilder()
  .showThreadInfo(false)  // (Optional) Whether to show thread info or not. Default true
  .methodCount(2)         // (Optional) How many method line to show. Default 2
  .tag("xxx")   // (Optional) Global tag for every log. Default PRETTY_LOGGER
  .build();

  Logger.addLogAdapter(new AndroidLogAdapter(formatStrategy) { //
    @Override public boolean isLoggable(int priority, String tag) {
      return BuildConfig.DEBUG;
    }
  });`

i had to add `Logger.clearLogAdapters();` before the addLogAdapter() to remove the double printing. Is this expected behavior?

**Comment by wuxinxi** [comment]
Probably because you set ‘Logger.addLogAdapter ' two times

**Comment by orhanobut** [comment]
What @wuxinxi said. Most probably you duplicate adapters. You need to ensure that you only initialize it once.
