### ISSUE TITLE
How can I add a timestamp to the header of the log?

### ISSUE THREAD

**Issue by frnusmartobjects** [orhanobut/logger#145]
I would like to be able to add a timestamp to the log independent of the log message itself, is this possible?

**Comment by wuxinxi** [comment]
Modify the source code, or add your own in a large string

**Comment by frnusmartobjects** [comment]
Adding my own in a large string (not sure what you mean but I understand that it it adding it as part of the log) is exactly the opposite I don't want to do.

I could modify the source code but I consider it to be a valuable feature to have in the logger to add custom information to the header of the log (i.e. where the method calls info is written)

**Comment by orhanobut** [comment]
Hi, there is a timestamp in LogCat already, isn't it enough? I'm just curious the use case you would be interested in.

**Comment by orhanobut** [comment]
Closing this one for now, we can re-open it again if needed
