### ISSUE TITLE
Feature Request: Ability to compile logger to not only logger log but also apex_debug.message in the same call

### ISSUE THREAD

**Issue by Code-Ergo-Sum** [orhanobut/logger#150]
As an Apex developer, I would like the ability to enable logger so that every logger log also performs an apex_debug.message with the same parameters. The idea being that sometimes it's easier to check one instead of the other, and vice versa. Logging a message both ways makes debugging more flexible.

**Comment by orhanobut** [comment]
Could you elaborate this one a little more with some examples? That'd be interesting. Maybe with the custom implementations, this can be done.

**Comment by orhanobut** [comment]
Closing this one for now, we can re-open definitely.
