### ISSUE TITLE
Not correct show logs in windows console

### ISSUE THREAD

**Issue by lmdic** [orhanobut/logger#153]
Windows 10 (64 bit)
Here result of logs in Android Studio:

[-14 17:13:52.353 31819-31819/? D/myproejct.MainActivity: onCreate: NATIVE_LOG
10-14 17:13:52.353 31819-31819/? D/PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-14 17:13:52.353 31819-31819/? D/PRETTY_LOGGER: │ Thread: main
10-14 17:13:52.353 31819-31819/? D/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
10-14 17:13:52.353 31819-31819/? D/PRETTY_LOGGER: │ Activity.performCreate  (Activity.java:5133)
10-14 17:13:52.353 31819-31819/? D/PRETTY_LOGGER: │    MainActivity.onCreate  (MainActivity.java:62)
10-14 17:13:52.353 31819-31819/? D/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
10-14 17:13:52.361 31819-31819/? D/PRETTY_LOGGER: │ onCreate: LIB_LOG
10-14 17:13:52.361 31819-31819/? D/PRETTY_LOGGER: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-14 17:13:52.384 31819-31823/? D/dalvikvm: GC_CONCURRENT freed 295K, 4% free 9013K/9344K, paused 3ms+3ms, total 37ms

OK. It's look good. 

But here result in windows console:

```
0-14 17:13:52.345 D/dalvikvm(31819): VFY: replacing opcode 0x6e at 0x0006
10-14 17:13:52.353 D/com.myproject.MainActivity(31819): onCreate: NATIVE_LOG
10-14 17:13:52.353 D/PRETTY_LOGGER(31819): ΓöîΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
10-14 17:13:52.353 D/PRETTY_LOGGER(31819): Γöé Thread: main
10-14 17:13:52.353 D/PRETTY_LOGGER(31819): Γö£ΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöä
10-14 17:13:52.353 D/PRETTY_LOGGER(31819): Γöé Activity.performCreate  (Activity.java:5133)
10-14 17:13:52.353 D/PRETTY_LOGGER(31819): Γöé    MainActivity.onCreate  (MainActivity.java:62)
10-14 17:13:52.353 D/PRETTY_LOGGER(31819): Γö£ΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöäΓöä
10-14 17:13:52.361 D/PRETTY_LOGGER(31819): Γöé onCreate: LIB_LOG
10-14 17:13:52.361 D/PRETTY_LOGGER(31819): ΓööΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
10-14 17:13:52.384 D/dalvikvm(31819): GC_CONCURRENT freed 295K, 4% free 9013K/9344K, paused 3ms+3ms, total 37ms
10-14 17:13:52.392 I/dalvikvm(31819): Failed resolving Landroid/support/v4/widget/DrawerLayout$1; interface 2556 'Landroid/view/View$OnApplyWindowInsetsListener;'
10-14 17:13:52.392 W/dalvikvm(31819): Link of class 'Landroid/support/v4/widget/DrawerLayout$1;' failed

```

**Comment by orhanobut** [comment]
Closing this one for now, we can re-open if the issue still exists
