### ISSUE TITLE
Logger.v,Logger.d,Logger.json not work?

### ISSUE THREAD

**Issue by hacket** [orhanobut/logger#154]
```java
formatStrategy = PrettyFormatStrategy.newBuilder()
	.showThreadInfo(true)
	.methodOffset(2)
	.methodCount(2)
	.tag("MyTag")
	.build();
Logger.addLogAdapter(new AndroidLogAdapter(formatStrategy));

Logger.v("my v message with MyTag");
Logger.i("my i message with MyTag");
Logger.d("my d message with MyTag");
Logger.w("my log message with my tag");
```

In the sample project,I add `Logger.v` , `Logger.i`  and `Logger.d`, but just `Logger.i` and `Logger.w` work. 

version :
`'com.orhanobut:logger:2.1.1'`

**Comment by REBOOTERS** [comment]
same problem ,I run the sample ,Logger.d  without any log in logcat window

**Comment by hueyra** [comment]
I get same problem , Logger.d without any log in logcat window

**Comment by bzn1120** [comment]
Did you init ?
or all do, you can see the lib is right, other lib also include Logger. or maybe device limit,
you can try   simulator or other devices.
发自网易邮箱大师


On 11/22/2017 10:53，zhujun<notifications@github.com> wrote：

I get same problem , Logger.d without any log in logcat window

**Comment by behindeye** [comment]
same problem,logger.json() does't work

**Comment by xinyangmaojian** [comment]
是不是没在 application 的oncreate方法里加   Logger.addLogAdapter(AndroidLogAdapter(PrettyFormatStrategy.newBuilder().tag("xxxxx").build()))

**Comment by EiChinn** [comment]
It may be that your mobile phone, such as Huawei mobile phone, prohibits the output of the background log, that is, it does not display Debug, Verbose level log in logcat. You need to enter into the project mode to allow output of these logs.
If you are using a Huawei mobile phone, you can enter *#*#2846579#*#* in the phone software(or  enter ()()2846579()()= in the Calculator software if you are using a Huawei pad) to enter the project mode, then: Background Settings - Background Debug - LOG Settings - select the "AP Log" checkbox

**Comment by orhanobut** [comment]
As others explained, it seems it's related to device. Unfortunately I can't do much about this from Logger point of view. I'd be happy though if someone wants to contribute to README with a FAQ section that explains this issue and potential solution.

**Comment by anderscheow** [comment]
This indeed is device problem. On my Xperia device, even using the native Log.d, it doesn't work, only work when I use Log.e or Log.i

**Comment by orhanobut** [comment]
Closing this one since can't do anything about this unfortunately.
