### ISSUE TITLE
Doesn't show colors in the consol

### ISSUE THREAD

**Issue by zo-chu** [orhanobut/logger#156]
So, everything is great but i tried the example from readme and there output has colors and in my console there is only red for errors and warning and all other things are verbose like white. Is there a way to get other colors as in the example output? that would be useful.

**Comment by orhanobut** [comment]
You can change the settings in Android Studio. Here is a [link](https://stackoverflow.com/questions/39993867/android-studio-logcat-colors-best-practice/39993868) that describe how to change it.
