### ISSUE TITLE
How to use in multiple modules/libraries with different FormatStrategy but one LogAdapter?

### ISSUE THREAD

**Issue by morris-stock** [orhanobut/logger#161]
I use ``logger`` in multiple modules/libraries, and setup adapter once, the problem is it's very hard to filter logs from different modules/libraries.

**Comment by orhanobut** [comment]
Do you mean to filter log messages or something else? If you just want to filter messages, tag could help.

**Comment by morris-stock** [comment]
Sure it is to filter log messages, but if I didn't miss anything, I should add tags to every log call or use a log wrapper.

What I really want is something like this:

assume I have `App`, `modA`, `modB`,
```
loggerApp = Logger.getDefaultLogger();
loggerA = Logger.getLogger("modA");
loggerB = Logger.getLogger("modB");
```
all loggers use the same `LogAdapter`, with the interface that I can do some basic configuration(e.g. tag prefix).

**Comment by orhanobut** [comment]
Unfortunately that's not possible to have multiple instance of Logger. As you mentioned, the easy way would be to use a wrapper.

**Comment by morris-stock** [comment]
OK, I will make a PR if some idea comes, now, let's close this issue, it's too old.
