### ISSUE TITLE
Log cannot be located~~~

### ISSUE THREAD

**Issue by LaymanInCoding** [orhanobut/logger#162]
Hi~I met a problem，my log couldn't locate where it happened,that's my setting code,could you tell me why？
 FormatStrategy formatStrategy = PrettyFormatStrategy.newBuilder()
                .showThreadInfo(false)  // (Optional) Whether to show thread info or not. Default true
                .methodCount(2)         // (Optional) How many method line to show. Default 2
                .methodOffset(5)        // (Optional) Hides internal method calls up to offset. Default 5
                .tag("Vissun")   // (Optional) Global tag for every log. Default PRETTY_LOGGER
                .build();
        Logger.addLogAdapter(new AndroidLogAdapter(formatStrategy) {
            @Override
            public boolean isLoggable(int priority, String tag) {
                return BuildConfig.DEBUG;
            }
        });

**Comment by LaymanInCoding** [comment]
it seems to be solved after reset the android studio，have youtried？ I'm not sure ,need time to remind it

**Comment by xushanning** [comment]
I'll try it. Thank you very much！

**Comment by LaymanInCoding** [comment]
hope that can help you , after all I really don't remember how i solved this . if i find it , i will give it to you immediately !

**Comment by LaymanInCoding** [comment]
`FormatStrategy formatStrategy = PrettyFormatStrategy.newBuilder()
                .tag("university")   // (Optional) Global tag for every log. Default PRETTY_LOGGER
                .build();
        Logger.addLogAdapter(new AndroidLogAdapter(formatStrategy) {
            @Override
            public boolean isLoggable(int priority, String tag) {
                return BuildConfig.DEBUG;
            }
        });`
in android studio 3.2.1,as I konw only set the tag，leave the rest properties keep default，then I see the location
