### ISSUE TITLE
used both in library and application , but print the same log twice

### ISSUE THREAD

**Issue by adaJQD** [orhanobut/logger#163]

**Comment by JohannesDev** [comment]
Are you using a multiline String with `.trimMargin()`? Logger seems to log twice when using `.trimMargin()`.

**Comment by JohannesDev** [comment]
Are you using a multiline String with `.trimMargin()`? Logger seems to log twice when using `.trimMargin()`.

**Comment by oleg404** [comment]
Same issue after upgrade to the newest version

**Comment by orhanobut** [comment]
Do you add `LogAdapter` twice? It should be used only once, that's the issue. It would be best if you can just initialize it in one place and use it in library.

**Comment by adaJQD** [comment]
yes, i have added `LogAdapter` twice !

**Comment by orhanobut** [comment]
Good to hear that. Closing this issue. 👍
