### ISSUE TITLE
文件日志中有<br>换行字符

### ISSUE THREAD

**Issue by lzyang187** [orhanobut/logger#164]
我往文件中打印了一个json字符串，打开此文件后有\<br\>字符，导致不能格式化此json字符串，如下：
1519372426477,2018.02.23 15:53:46.477,DEBUG,filetag,{ \<br\>   "key": "value", \<br\>   "list": [ \<br\>     "a", \<br\>     "b", \<br\>     1 \<br\>   ] \<br\> }

**Comment by orhanobut** [comment]
I can't help on this one unfortunately since It's not clear to me what is the issue. Closing.
