### ISSUE TITLE
1.5 does not work

### ISSUE THREAD

**Issue by joezorry** [orhanobut/logger#17]
I updated to 1.5, in our gradle files (since we need the stack-trace crash fix), but it does not recognise the classes from the library.

Even if I put the `.aar` locally in the project it does not work.

1.4 works perfectly, something wrong with the build that were uploaded to mavenCentral?

**Comment by orhanobut** [comment]
can you clean and sync the gradle again? 1.5 is in maven it seems. https://oss.sonatype.org/content/repositories/releases/com/orhanobut/logger/1.5/

**Comment by joezorry** [comment]
Yeah, I know, I even downloaded that `.aar` and tried it locally, still nothing, can't recognise the `Logger` class (or `LogLevel`)

**Comment by joezorry** [comment]
Just to give some more info I tried, cleaning, both in terminal and in AS, I also tried with and without the `@aar` appended on the dependency.

And I've confirmed `mavenCentral()` is in the repository list, since we get more dependencies from there, like the 1.4 version.

**Comment by orhanobut** [comment]
I need to investigate thoroughly. I guess that 1.4 works because of the cache I think. The problem might be maven itself.

**Comment by joezorry** [comment]
I actually tried this again, removed gradle caching, and still does not work.

But I built my own from master, and bumped the version to 1.6 and it works, actually don't know what the problem might be, but we are five people having this problem here but we all run the same project, so the problem could be in our project.

**Comment by orhanobut** [comment]
Tonight I'll check it this issue, very annoying one. I couldn't have enough time yesterday really.  Thanks for the feedback though. It will help a lot for sure.

**Comment by orhanobut** [comment]
Do you still have this issue?

**Comment by joezorry** [comment]
Actually compiled our own and uploaded to our own artifactory maven server. So I haven't tried it since friday, but then we did have this issue. However, looking back it could be that the `w` method was not there, since we rely on it.

**Comment by orhanobut** [comment]
with v1.9 all above issues should be fixed.
