### ISSUE TITLE
I want just log some content in file ，but  always log all of them。

### ISSUE THREAD

**Issue by Farubaba** [orhanobut/logger#172]

**Comment by Farubaba** [comment]
How can i just log some content in file ，but always log all of them default。I tried to extend LoggerPrinter to add method like "logToFile()", but it's not a Public class. That all I want is to control witch LogAdapter and when can output log. not all the LogAdapter always output log every time.

**Comment by orhanobut** [comment]
Have you tried filter them by using `isLoggable` method? You can override and choose the log message by tag or by priority.

```java
LogAdapter logAdapter = new DiskLogAdapter() {
  @Override public boolean isLoggable(int priority, String tag) {
    return tag.equals("my_filter");
  }
};
Logger.addLogAdapter(logAdapter);
```

**Comment by orhanobut** [comment]
Closing this issue for now, we can reopen if the given solution doesn't work for you.
