### ISSUE TITLE
Android Studio 3.1 problem

### ISSUE THREAD

**Issue by FongMi** [orhanobut/logger#173]
![image](https://user-images.githubusercontent.com/3471963/37944286-9005ef16-31ad-11e8-8e70-3a0a5866f72a.png)

format is wrong

**Comment by imknown** [comment]
Reported. https://issuetracker.google.com/issues/76448010

**Comment by orhanobut** [comment]
I wonder what caused this issue. I haven't updated to 3.1 version yet but will check it out definitely. Thanks for the report.

**Comment by enginebai** [comment]
I have the same problem after upgrading Android Studio to v3.1, the temporary workaround is unselected all options from `Configure Logcat Header`.

<img width="977" alt="2018-03-28 11 54 38" src="https://user-images.githubusercontent.com/3387462/38008137-a81bfaaa-327f-11e8-8968-9dcaa2acc017.png">

**Comment by GregoryHo** [comment]
The problem can be produce when trying to log message at very small time intervals, maybe some behavior of logcat has been changed in Android Studio v3.1.

**Comment by FongMi** [comment]
Yes, android studio 3.1 is display based on milliseconds.
![default](https://user-images.githubusercontent.com/3471963/38122464-baf3efc8-3407-11e8-912c-e8f0baa1cca7.png)

**Comment by noState** [comment]
Yes，I Update As to V3.1.0 is display

**Comment by linwoain** [comment]
```java
public class LogCatStrategy implements LogStrategy {

  @Override public void log(int priority, String tag, String message) {
    Log.println(priority, randomKey() + tag, message);
  }

  private int last;

  private String randomKey() {
    int random = (int) (10 * Math.random());
    if (random == last) {
      random = (random + 1) % 10;
    }
    last = random;
    return String.valueOf(random);
  }
}
PrettyFormatStrategy strategy = PrettyFormatStrategy.newBuilder()
        .showThreadInfo(false)
        .logStrategy(new LogCatStrategy())
        .methodCount(1)
        .tag("Ad_STK")
        .build();
    com.orhanobut.logger.Logger.addLogAdapter(new AndroidLogAdapter(strategy) {
      @Override public boolean isLoggable(int priority, String tag) {
        return BuildConfig.DEBUG;
      }
    });
```

result like this:

![image](https://user-images.githubusercontent.com/5582899/38192609-3808e1fe-36a0-11e8-94a5-1e02c6e18242.png)

**Comment by FongMi** [comment]
@linwoain Thanks, It's works.

**Comment by noState** [comment]
@linwoain But there has a number   how to delete it   i`m cleanliness

**Comment by noState** [comment]
@linwoain I known that you keep deffirent tags to resolve the problem， but i`m cleanliness， sorry，，，

**Comment by linwoain** [comment]
@noState 
```java
public class LogCatStrategy implements LogStrategy {

    private HandlerThread thread = new HandlerThread("thread_print");
    private Handler handler ;
    private long lastTime = SystemClock.uptimeMillis();
    private long offset = 5;

    public LogCatStrategy() {
        thread.start();
        handler = new Handler(thread.getLooper());
    }

    @Override
    public synchronized void log(final int priority, final String tag, @NonNull final String message) {

        lastTime += offset;
        if (lastTime < SystemClock.uptimeMillis()) {
            lastTime = SystemClock.uptimeMillis() + offset;
        }
        final long tmp = lastTime;
        handler.postAtTime(new Runnable() {
            @Override
            public void run() {
                Log.println(priority, tag, message);
            }
        }, tmp);

    }

PrettyFormatStrategy strategy = PrettyFormatStrategy.newBuilder()
        .showThreadInfo(false)
        .logStrategy(new LogCatStrategy())
        .methodCount(1)
        .tag("Ad_STK")
        .build();
    com.orhanobut.logger.Logger.addLogAdapter(new AndroidLogAdapter(strategy) {
      @Override public boolean isLoggable(int priority, String tag) {
        return BuildConfig.DEBUG;
      }
    });
```
maybe u like this,but it can make log print slowly when print much more line at the same time.

**Comment by noState** [comment]
@linwoain thank u so much，，，

**Comment by joshualyon** [comment]
@FongMi should this issue be left open until it gets fixed in master? I noticed that @orhanobut mentioned this issue when closing other similar issues.

**Comment by FongMi** [comment]
OK, I will reopen the issue.

**Comment by orhanobut** [comment]
Yes, let's keep this issue open for tracking this issue. 👍

**Comment by orhanobut** [comment]
I'll check this issue with Android Studio team to see whether they will consider this change as a bug and fix it with the upcoming versions or not. If it will continue this way, we can consider making some changes to avoid this issue. Quite annoying though.

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/blob/fb09c548b015d96b80b5dfa0e4a496e871f69aa4/arms/src/main/java/com/jess/arms/http/log/DefaultFormatPrinter.java#L188

**Comment by eyronic** [comment]
@jeffreyliu8 Same date, time and tag on the next line will remove the date, time and tag, showing only the message.

**Comment by hvsimon** [comment]
It will be fixed in Android Studio 3.2. See https://issuetracker.google.com/issues/77305804#comment10

**Comment by FongMi** [comment]
Android Studio 3.2 has been fixed the problem.

**Comment by RossPoom** [comment]
Still exists in "Android Studio 3.5"

**Comment by jibenziliao** [comment]
I have the same issue in "Android Studio 3.5"

**Comment by jibenziliao** [comment]
![image](https://user-images.githubusercontent.com/12134347/64318475-bf496300-cfec-11e9-897f-8a9fcaeb0403.png)
![image](https://user-images.githubusercontent.com/12134347/64318495-c83a3480-cfec-11e9-8660-af02917ad1ba.png)

**Comment by jeffreyliu8** [comment]
Click Logcat, not debug.
