### ISSUE TITLE
Why my log format is not aligned

### ISSUE THREAD

**Issue by monkey008** [orhanobut/logger#176]
![tim 20180328100329](https://user-images.githubusercontent.com/14806653/38004626-b00d0124-326f-11e8-8dff-adc087e4ca2d.jpg)

AndroidStudio version:3.1

`api 'com.orhanobut:logger:2.1.1'`

```
        Logger.addLogAdapter(new AndroidLogAdapter() {
            @Override
            public boolean isLoggable(int priority, String tag) {
                return Config.isDebug || Config.showLog;
            }
        });
```

**Comment by monkey008** [comment]
Okay, sorry, I didn't read README.md in detail. I just discovered this

> Make sure that wrap option is disabled

**Comment by monkey008** [comment]
I configured all the options and it still looks untidy

![tim 20180328104501](https://user-images.githubusercontent.com/14806653/38005876-4d733f6e-3275-11e8-9a87-358ac5b6530f.jpg)
![tim 20180328104527](https://user-images.githubusercontent.com/14806653/38005877-4dc18d04-3275-11e8-926e-903d780f680b.jpg)

**Comment by orhanobut** [comment]
It seems that something has changed with Android Studio 3.1. I think there was another similar issue like this. #173 We can follow up this issue in there. Therefore closing this one.
