### ISSUE TITLE
Android Studio 3.2 - wrong log version 2.2.0

### ISSUE THREAD

**Issue by zloyreznic** [orhanobut/logger#177]
https://image.prntscr.com/image/NZHm7EHSRZqMkz3tiqPIWg.png

![nzhm7ehsrzqmkz3tiqpiwg](https://user-images.githubusercontent.com/3604074/38028238-02fb0022-329b-11e8-8cde-3c1f7b41ee4a.png)

**Comment by MiloHwb** [comment]
Not just Android Studio 3.2, also Android Studio 3.1 has the same problem

**Comment by orhanobut** [comment]
It seems a change in studio. There is another open issue with the same problem. #173 . We can follow up on that one. Closing this one due to duplication.
