### ISSUE TITLE
Only a log, but print many times（repeated）?

### ISSUE THREAD

**Issue by codeinmyself** [orhanobut/logger#181]
Just like:
E/PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/PRETTY_LOGGER: │ Thread: main
E/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
E/PRETTY_LOGGER: │ Handler.handleCallback  (Handler.java:730)
E/PRETTY_LOGGER: │    RecordedActivity$6.run  (RecordedActivity.java:310)
E/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
E/PRETTY_LOGGER: │ 执行run方法结束！
E/PRETTY_LOGGER: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/PRETTY_LOGGER: │ Thread: main
E/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
E/PRETTY_LOGGER: │ Handler.handleCallback  (Handler.java:730)
E/PRETTY_LOGGER: │    RecordedActivity$6.run  (RecordedActivity.java:310)
E/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
E/PRETTY_LOGGER: │ 执行run方法结束！

**Comment by orhanobut** [comment]
- Which android studio version do you have?
- Can you show me how did you initialize Logger?
- Can you show me the code snippet you are trying to log?

**Comment by codeinmyself** [comment]
Thanks for attention.
**Android  Studio version: 3.0**
I initialize logger just like:
```
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_product_type);
        Logger.addLogAdapter(new AndroidLogAdapter() {
            @Override public boolean isLoggable(int priority, String tag) {
                return BuildConfig.DEBUG;
            }
        });
}
``` in every activities.

And use it by:
Logger.e("wrong！");

**Comment by orhanobut** [comment]
That's the issue. You only need to initialize it once, each time you use `addLogAdapter` it adds another adapter. I suggest that you do the initialization in your custom application class. 

```java
public class MyApplication extends Application {

    @Override public void onCreate() {
        super.onCreate();
        
        Logger.addLogAdapter...
    }
}
```

**Comment by orhanobut** [comment]
Closing this issue for now. The issue should be solved by initializing only once.

**Comment by codeinmyself** [comment]
Thanks for your guidance and patience.
