### ISSUE TITLE
Suggestion: Make the API compatible with android.util.Log

### ISSUE THREAD

**Issue by curioustechizen** [orhanobut/logger#2]
Consider making the API compatible with `android.util.Log` so that switching to this library doesn't involve making too many changes to existing code. For example, consider adding the following even if you don't use the `tag` parameter:

```java
public static void d(String tag, String message);
```

Of course one might argue that users of this library should wrap the call to `Logger.d()` within their own utility class if they want to seamlessly switch to it from `android.util.Log`. But maybe it is easier if the library provides this out of the box.

As an example, take a look at [this Logging library](https://github.com/curioustechizen/android-xlog) that can be used just by changing the import statements and no other code changes.

**Comment by Rainer-Lang** [comment]
+1

**Comment by orhanobut** [comment]
I agree with the compatible part but on the other hand, current log signature might cause problem for pretty print (drawing table layout). All logs must have the same TAG. I think it might also be annoying if you want to use both if both has the same name. Let me check If I can come up with another idea or I'm open for any other ideas to make it more compatible as well as not affecting anything.

**Comment by curioustechizen** [comment]
@orhanobut Oh I did not realize that the table layout works best if all tags have the same name! Yeah in that case adding a tag parameter might not make sense. 

One option to make it compatible is to add overloaded versions of methods that take tag parameters but simply ignore the tag.

In any case this is a great library that I'm going to use in new projects.

**Comment by orhanobut** [comment]
@curioustechizen thank you :) I'm happy that it is useful to other developers as well. For the other thing, I think it will mislead if we ignore the tag when they provide. In any case, client needs to change something for the usage now. By changing Log.d(TAG, "test) to Logger.d("test").

**Comment by orhanobut** [comment]
with v1.3, I've added custom tag feature. I think this will meet the needs now.
