### ISSUE TITLE
"Jump to source" doesn't work in Eclipse

### ISSUE THREAD

**Issue by JollyJiang** [orhanobut/logger#22]
Does it only work in AndroidStudio?

**Comment by orhanobut** [comment]
I haven't tried with the eclipse. Eclipse may require another approach for that. I need to check it.

**Comment by MIkeeJY** [comment]
I've faced the same problem in Eclipse too

**Comment by orhanobut** [comment]
Unfortunately I can't do that much about this issue since it will require different solutions for different IDE's it seems, therefore I'm closing this issue. But I'll be happy for any PR if there is a proper solution
