### ISSUE TITLE
关于源码release版本无法运行，只有debug才能打印日志。不知道为何，谁明白告诉我一声。

### ISSUE THREAD

**Issue by yugu88** [orhanobut/logger#234]
Please try to fill all questions below before submitting an issue.

- Android studio version:
- Android gradle plugin version:
- Logger version:2.2.0
- Emulator/phone information:
- If possible, please add how did you initialize Logger?
- Is it flaky or does it happen all the time?

**Comment by luckWenTao** [comment]
isLoggable改成true也没用
