### ISSUE TITLE
No work on Android X 

### ISSUE THREAD

**Issue by FetFrumos** [orhanobut/logger#239]
Hello, orhanobut/logger not work on Android X. Log file is not created.

- Android studio version - 3.6.1
- Android gradle plugin version - 3.5.1
- Logger version - com.orhanobut:logger:2.2.0
- Emulator/phone information -Samsung 9(Android X)
- If possible, please add how did you initialize Logger? Yes

        Logger.addLogAdapter(new DiskLogAdapter());

- Is it flaky or does it happen all the time? Yes

**Comment by FetFrumos** [comment]
fixed

**Comment by kulnaman** [comment]
@FetFrumos  can you please elaborate about the fix, I am also facing similar issues
