### ISSUE TITLE
Not found in repository

### ISSUE THREAD

**Issue by shelterless** [orhanobut/logger#25]
Error:Artifact 'logger.aar (com.github.orhanobut:logger:v1.8-tag)' not found.
Searched in the following locations:
    https://jitpack.io/com/github/orhanobut/logger/v1.8-tag/logger-v1.8-tag.aar

**Comment by jitpack-io** [comment]
@shelterless Seems to work fine.

**Comment by orhanobut** [comment]
It is also working for me. Might be something different.
