### ISSUE TITLE
How to output Logger.e to console when running junit test in android studio

### ISSUE THREAD

**Issue by henrytao-me** [orhanobut/logger#26]
Hi there,
The title is pretty obvious. I am be able to print log to console with `e.printStackTrace()` when running unit test in android studio but `Logger.e(JsonUtils.class.getName(), jsonString, e)`.

Thanks in advance!

**Comment by orhanobut** [comment]
Hi, let me check this issue.

**Comment by IgorGanapolsky** [comment]
I too am curious how to log console output from junit test.  Any update on this?

**Comment by orhanobut** [comment]
This is something I'm working on but on a different level though. I'm trying to show the output log quite differently for unit tests.

**Comment by IgorGanapolsky** [comment]
Well, silly me.  One can just use `System.out.println()`, and it will log.

**Comment by orhanobut** [comment]
I'll add a built-in LogAdapter to support System logs.

**Comment by orhanobut** [comment]
With a custom `LogStrategy` it's doable. Long time that I couldn't check this issue. One of the earliest issues. Closing this one since It can be done easily with custom `LogStrategy`. Looks quite nice in tests.

```kotlin
val formatStrategy = PrettyFormatStrategy.newBuilder()
    .logStrategy { priority, tag, message -> println(message) }
    .build()
Logger.addLogAdapter(AndroidLogAdapter(formatStrategy))
```
