### ISSUE TITLE
Feature Request: Allow json to be printed to a different log level

### ISSUE THREAD

**Issue by RadicalMonkey** [orhanobut/logger#29]
Relates to #28 

Is there a way to allow the json string to be logged into a different log level?

**Comment by orhanobut** [comment]
This will extend the scope but you can create an abstraction and move away all log details, within this wrapper class you can actually decide what to show/hide in which order etc. But for now I won't change the scope unfortunately due to maintenance reasons

**Comment by van048** [comment]
marked
