### ISSUE TITLE
Suggestion: Change the TAG only in one log

### ISSUE THREAD

**Issue by Aracem** [orhanobut/logger#3]
First of all, congratulations for the library, veeeery awesome :) 

Can you add an option to change the TAG only for one log? Something like:

Logger.e("TAG", "Message");

Thank you!

**Comment by orhanobut** [comment]
First of all thank you :)
Unfortunately current tag cannot be changed due to drawing table layout, otherwise it will have a bad display. But specific tag can be shown at the top of table layout such as thread row. I'll add this feature. I think it will be useful in some cases

**Comment by Aracem** [comment]
That will be awesome!
Thank you so much!!!

**Comment by orhanobut** [comment]
Instead of another row, I've added custom tag feature. In order to have better filter, it will be concat with the static TAG.
```java
Logger.d(TAG, "test");
```
