### ISSUE TITLE
How to integrate to the Timber?

### ISSUE THREAD

**Issue by acdsee3003** [orhanobut/logger#31]
I'm using https://github.com/JakeWharton/timber, then I have a question.
The log : 
RequestListener.onRequestSuccess  (RequestListener.java:46)
 ║    Timber.d  (Timber.java:23)
 ║       Timber$1.d  (Timber.java:136)
 ║          Timber$Tree.d  (Timber.java:245)
 ║             Timber$Tree.prepareLog  (Timber.java:319)
 ║                PrettyDebugTree.log  (PrettyDebugTree.java:33)

How to get rid of  : 
 ║    Timber.d  (Timber.java:23)
 ║       Timber$1.d  (Timber.java:136)
 ║          Timber$Tree.d  (Timber.java:245)
 ║             Timber$Tree.prepareLog  (Timber.java:319)
 ║                PrettyDebugTree.log  (PrettyDebugTree.java:33)

I just want : RequestListener.onRequestSuccess  (RequestListener.java:46)

**Comment by orhanobut** [comment]
can you show me the logger settings and log call usage?

**Comment by acdsee3003** [comment]
@orhanobut 
The PrettyDebugTree.java : 
public class PrettyDebugTree extends Timber.Tree {

    public PrettyDebugTree() {
        Logger.init("PrettyLogger")
                .hideThreadInfo()
                .setMethodCount(6)
                .setLogLevel(LogLevel.FULL);
    }

    @Override
    protected void log(int priority, String tag, String message, Throwable t) {
        switch (priority) {
            case Log.VERBOSE:
                Logger.v(message);
                break;
            case Log.DEBUG:
                Logger.d(message);
                break;
            case Log.INFO:
                Logger.i(message);
                break;
            case Log.WARN:
                Logger.w(message);
                break;
            case Log.ERROR:
                Logger.e(t, message);
                break;
            case Log.ASSERT:
                Logger.wtf(message);
                break;
        }

    }
}

And add this class to Timber :
Timber.plant(new PrettyDebugTree());

Print log :
Timber.d("some message");

**Comment by orhanobut** [comment]
method count is 6, you need to decrease it to 1.

**Comment by acdsee3003** [comment]
@orhanobut  
If set the method count to 1 ,log will print PrettyDebugTree. Log (PrettyDebugTree. Java: 33), but i want to print RequestListener.onRequestSuccess (RequestListener.java:46) .
I mean, can you provide a method to set up the MethodStack range?

**Comment by orhanobut** [comment]
I get your issue now. well unfortunately there is no this option now. but can be added, apparently it will be very useful for these situations.

**Comment by acdsee3003** [comment]
@orhanobut thank you.

**Comment by orhanobut** [comment]
With the new version, you should be able to avoid these methods.

```java
Logger.init().
    .setMethodOffset(5);
```

**Comment by acdsee3003** [comment]
@orhanobut It does work. Thanks.

**Comment by orhanobut** [comment]
cheers

**Comment by riinav** [comment]
Thanks @orhanobut and @acdsee3003 
I have configured Timber with this library to pretty print all the Logging.

This is the best Logging lib I have came accross :)

**Comment by zhupengxiang** [comment]
@rinav  What's the final solution?
