### ISSUE TITLE
how is this thread safe?

### ISSUE THREAD

**Issue by talarari** [orhanobut/logger#35]
I see that there's a single printer instance saved on a static member in logger.java
so when i do this simultaneously from 2 threads:
thread1 - logger.t("tag1").i("log1")
thread2 - logger.t("tag2").i("log2")

it seems very likely that logs will be written with wrong tags.

or am i missing something?

**Comment by orhanobut** [comment]
Logger uses threadlocal for one use tags, which means every thread can store tag individually

**Comment by talarari** [comment]
Will this be OK with two tags from the same thread from two async actions?

**Comment by yekmer** [comment]
For two async actions, you need two threads at least. So it will be working for sure.

**Comment by talarari** [comment]
Not necessarily, you can run multiple async actions on the same thread. 
I'm using rx java, pretty sure it pools threads.
I'll give it a try to see if I get switched tags

**Comment by yekmer** [comment]
For both rxjava thread, it will come from another thread and will have a callback in one thread. So it will not be a problem
