### ISSUE TITLE
android:allowBackup should not be used in library

### ISSUE THREAD

**Issue by baoyongzhang** [orhanobut/logger#37]
Error:(8, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:8:9
  	is also present at com.orhanobut:logger:1.10:11:18 value=(true)
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5 to override

**Comment by orhanobut** [comment]
good point, need to remove those all auto generated codes indeed, thanks

**Comment by orhanobut** [comment]
fixed in v11
