### ISSUE TITLE
Timber support

### ISSUE THREAD

**Issue by Kisty** [orhanobut/logger#39]
Love the look of this library. Would be awesome to use with @JakeWharton's Timber library https://github.com/JakeWharton/timber.

**Comment by orhanobut** [comment]
thanks! I don't know how timber works exactly, need to check it but you can also see the following issue to check how they integrated. https://github.com/orhanobut/logger/issues/31

**Comment by sahal2080** [comment]
+1. I want my timber to look pretty :b

**Comment by Kisty** [comment]
Hey thanks for adding Timber instructions to the README.
