### ISSUE TITLE
2 Suggestions: Debug vs Prod and Logger call

### ISSUE THREAD

**Issue by appmath** [orhanobut/logger#4]
Yes, I agree this is a really cool logger. Before I can make the switch I would love to see something like Jake Wharton's Timber's approach:
if (BuildConfig.DEBUG) {
    Timber.plant(new Timber.DebugTree());
} else {
    Timber.plant(new CrashReportingTree());
}  

The other suggestion is kind of silly, like most of us I am very lazy and typing
L.v("test2"); or even 
Lg.v("test2"); is faster/simpler than typing
Logger.v("test2");

**Comment by orhanobut** [comment]
Thanks for the feedback :)
- First suggestion looks good but I have some drawbacks and confirmations needed. (I'll come back later for this one again).
- I think everyone has different taste of code style, I prefer the latter for example :) I think this will be up to developer if they want to wrap or not.

**Comment by slidenerd** [comment]
Best idea, rename the Logger class to L, it ll minimize typing highly and change the methods to L.m for debug, L.v for verbose, L.t for Toast and so on...

**Comment by yekmer** [comment]
I do not think class name L describes what it does well. But it is so easy if you want to do. In your app just create a class named L and wrote methods just calls Logger.m inside it.

**Comment by jaredrummler** [comment]
I name my logger class `L`. It doesn't describe it well but the static factory methods `v`, `d`, `i`, `w`, `e` don't either.

I would also suggest formatting the String like [Timber](https://github.com/JakeWharton/timber/blob/master/timber/src/main/java/timber/log/Timber.java#L292-295) does.

I added the pretty logging to my class. https://gist.github.com/jaredrummler/eda77edc62d35d4344e6

```java
private static final L.Logger LOG = new L.Logger("LOGTAG").setPrettyPrint(true);
...

LOG.e("Example: int: %d boolean: %b char: %c", someException, 1, true, 'a');
```

**Comment by HappyDr0id** [comment]
About "Logger.v VS L.v", don't forget that Android Studio's live templates are very useful for that kind of laziness ;)

**Comment by null-dev** [comment]
Just have remove any non-static fields and methods from the Logger class and now you can make unlimited alias classes by just extending Logger.class!

**Comment by orhanobut** [comment]
I think most of the discussion has been either implemented or some is not going to be, thus going to close this issue.
