### ISSUE TITLE
support slf4j?

### ISSUE THREAD

**Issue by crazier9527** [orhanobut/logger#41]
Thanks very much for this library.

Is it possible to support slf4j?

Thanks

**Comment by orhanobut** [comment]
thanks, I haven't used slf4j before to be honest, as I understand you want to be able to use slf4j instead of android.util.Log in the logger right?

**Comment by crazier9527** [comment]
: )I want to use as a log slf4j facade, in fact, I have used the slf4j + logback for android in my project, and now I do not want to modify business logic, switch directly to slf4j + this library.

slf4j:http://www.slf4j.org/     
The Simple Logging Facade for Java (SLF4J) serves as a simple facade or abstraction for various logging frameworks (e.g. java.util.logging, logback, log4j) allowing the end user to plug in the desired logging framework at deployment time.

**Comment by orhanobut** [comment]
I'll add this as soon as possible as optional, seems nice

**Comment by orhanobut** [comment]
I changed the constructor to enable log tool injection. You could use any other log tool and pass it to logger
```java
.setLogTool(..)
```
