### ISSUE TITLE
Can you more optimization for the logger?

### ISSUE THREAD

**Issue by YanceyLee** [orhanobut/logger#42]
1.public void json(String json){

  + add if (settings.getLogLevel() == LogLevel.NONE) {

      return;

    }

.........
}

public void xml(String xml){

 +  add if (settings.getLogLevel() == LogLevel.NONE) {

      return;

    }

.........

}

2.public enum LogLevel {

  FULL,

  NONE

+ add INFO

+add DEBUG

+add ERROR

.............
}

3.........

**Comment by orhanobut** [comment]
Logger already has this condition check in the main method.
```java
  private synchronized void log(int logType, String msg, Object... args) {
    if (settings.getLogLevel() == LogLevel.NONE) {
      return;
    }
```
