### ISSUE TITLE
Fatal Exception: java.util.MissingFormatArgumentException Format specifier: 20O

### ISSUE THREAD

**Issue by ssuukk** [orhanobut/logger#45]
When using Logger.d("Some text",exception) I'm getting the following error:

java util.Formatter.getArgument (Formatter.java:1111)
java.lang.String.format (String.java:1973)
com.orhanobut.logger.LoggerPrinter.createMessage (LoggerPrinter.java:346)
com.orhanobut.logger.LoggerPrinter.log (LoggerPrinter.java:211)
com.orhanobut.logger.LoggerPrinter.d (LoggerPrinter.java:109)
com.orhanobut.logger.Logger.d (Logger.java:49)

**Comment by ssuukk** [comment]
OK, my bad. I should've rtfm. Sorry.

**Comment by orhanobut** [comment]
:+1:
