### ISSUE TITLE
the android studio 1.3.2 didn't show the thread message. so how can i setting it?

### ISSUE THREAD

**Issue by cffz0225** [orhanobut/logger#47]
i setting it in application oncreate method 
         Logger.init("MeetingPac");               // default PRETTYLOGGER or use just init()
         Logger.d("testa");

the show just is : "09-17 17:15:19.276  11859-11859/com.sqlview.meetingpac D/MeetingPac﹕ ║ testa"

so the thread message?

**Comment by orhanobut** [comment]
Hmm, that's very interesting, does it happen only with 1.3.2 or it just happens with every version of android studio? Sorry for the late reply btw

**Comment by orhanobut** [comment]
Is this issue still exists?

**Comment by orhanobut** [comment]
I'll close the issue and if the issue still exists, we can reopen it.
