### ISSUE TITLE
Making a Jar

### ISSUE THREAD

**Issue by emreaktrk** [orhanobut/logger#49]
Hi Orhan,

Thats a great project. Cong. I am trying to import this project as jar. Is it possible? Can you provide a jar for lastest version?

Thanks.
Good luck

**Comment by emreaktrk** [comment]
I did a dirty way which is cloned project and opened .aar file with winrar and get classes.jar from inside it.

**Comment by orhanobut** [comment]
Hi @emreaktrk , sure that's reasonable. I'll check how I can make it automated, manual uploading could be out of control after a while :)

**Comment by orhanobut** [comment]
Added aar file into the release section for now. 
https://github.com/orhanobut/logger/releases/tag/1.12

I think that would be easy for everyone.

**Comment by emreaktrk** [comment]
Great job. 

On the otherhand, project dosent have any resourece as i know. So that we can also export as jar but need  little bit configration. :/

**Comment by orhanobut** [comment]
I'm always open for the contributions :)
