### ISSUE TITLE
Please update the documentation concerning "Use Soft Wraps"

### ISSUE THREAD

**Issue by appmath** [orhanobut/logger#5]
To inform the users that to get the same pretty output, they need to disable "Use Soft Wraps". I spent a few minutes wondering why I had some an awful formatting.
With "Use Soft Wraps" enabled:
![image](https://cloud.githubusercontent.com/assets/4098053/6786745/6b9ab438-d14b-11e4-8f99-2bba62e6c560.png)

Disabled:
![image](https://cloud.githubusercontent.com/assets/4098053/6786663/fb003bee-d14a-11e4-96c5-923ecdc4b82a.png)

**Comment by orhanobut** [comment]
@appmath Thank you! for this feedback, apparently very crucial.

**Comment by orhanobut** [comment]
Readme updated. thanks again.
