### ISSUE TITLE
I must init tag firstly, is that right?

### ISSUE THREAD

**Issue by xinmeng1** [orhanobut/logger#50]
I must init tag firstly, is that right?  
Logger.init("TAG");

Or, I will get exception of java.lang.NullPointerException

**Comment by orhanobut** [comment]
Actually it shouldn't be necessary but recent changes made init as dependency. You need to call init() or init(TAG). But I'll make a fix to change this dependency.

**Comment by xinmeng1** [comment]
Got it, thanks very much. 
I think we need give a prompt for novice(like me) , or I think some one will always got exceptions after only try logger.

**Comment by orhanobut** [comment]
I'll add it to readme file to avoid confusion. thanks for the feedback

**Comment by xinmeng1** [comment]
Thanks very much~

**Comment by orhanobut** [comment]
@xinmeng1 with 2.0 it's required to init with new adapter approach.
