### ISSUE TITLE
Attempt to invoke virtual method 'com.orhanobut.logger.LogLevel com.orhanobut.logger.Settings.getLogLevel()' on a null object reference

### ISSUE THREAD

**Issue by jk2K** [orhanobut/logger#52]
alert error When use Logger.d("fdjal")
```
Attempt to invoke virtual method 'com.orhanobut.logger.LogLevel com.orhanobut.logger.Settings.getLogLevel()' on a null object reference
```

version: 1.12

**Comment by jk2K** [comment]
I found the solution, must initialize Logger in the application class, if i do not, program will alert the error

initialization is not optional?

**Comment by jk2K** [comment]
I found the solution, must initialize Logger in the application class, if i do not, program will alert the error

initialization is not optional?

**Comment by orhanobut** [comment]
:+1:
