### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by emreaktrk** [orhanobut/logger#54]
Hi Orhan,

I need a proguard config. Without it, cant use library because Logger.init() function throws method not found exception. Can you provide one?

Thanks Emre

**Comment by orhanobut** [comment]
Hi Emre,
Currently I'm out of city, I'll provide config in a few days

**Comment by SmartDengg** [comment]
Hi Orhan,

Do you come back? I need a proguard config, too.

**Comment by qq8057656qq** [comment]
Hi Orhan,

I need a proguard config too,can you provide it? tks :)

**Comment by orhanobut** [comment]
I added this issue to my backlog.

**Comment by mrArtCore** [comment]
Hi guys! Can't find proguard-rules . If someone got, could you share it please ))

**Comment by emreaktrk** [comment]
You can easily keep all the packages and etc in this library like

-keep public class com.myapp.customcomponents.** {
  public protected *;
}
