### ISSUE TITLE
Cannot add lib to project

### ISSUE THREAD

**Issue by mchenani** [orhanobut/logger#57]
Hey there
I've tried many time to add library into my project but I got below error:
Gradle sync failed: Could not find com.github.User:Repo:Tag.

**Comment by orhanobut** [comment]
can you show how you try to add the dependency?

**Comment by zuoer8676** [comment]
maybe the gradle version is not correct

**Comment by flykule** [comment]
Try to update gradle version to 2.2.1-all in gradle.properties

**Comment by orhanobut** [comment]
I'm closing this issue since we couldn't get enough feedback on related issue. If the issue still exists, we can reopen it.
