### ISSUE TITLE
 android:allowBackup="true"

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [orhanobut/logger#67]
please change android:allowBackup="true" to android:allowBackup="false"

**Comment by orhanobut** [comment]
It's already false.

**Comment by Lee-Wang-Jing** [comment]
compile 'com.orhanobut:logger:1.3'

**Comment by orhanobut** [comment]
On the recent versions, it is false. Why don't you use the latest version?

**Comment by Lee-Wang-Jing** [comment]
Thanks,I use 1.12 is ok

**Comment by orhanobut** [comment]
👍
