### ISSUE TITLE
Please support log out list 

### ISSUE THREAD

**Issue by ysmintor** [orhanobut/logger#70]
As you know, some user really need print the list directory, please add this feature.

**Comment by orhanobut** [comment]
What do you mean by list directory? Can you give me more details?

**Comment by ysmintor** [comment]
Sorry, I didn't describe this problem clearly. What I mean is the features that print List,Set, Map directly.
```java

List<Person> list1 = new ArrayList<>();
for(int i = 0; i < 4; i++){
    list1.add(person);
}
Logger.d(list1);


double[][] doubles = {{1.2, 1.6, 1.7, 30, 33},
                {1.2, 1.6, 1.7, 30, 33},
                {1.2, 1.6, 1.7, 30, 33},
                {1.2, 1.6, 1.7, 30, 33}};
Logger.d(doubles);
```

**Comment by ZengTianShengZ** [comment]
use for(){}

**Comment by orhanobut** [comment]
Can you try the latest version (1.14). Logger.d() accepts any collections now.

**Comment by ysmintor** [comment]
Great!

**Comment by marcJV** [comment]
Is this issue resolved? If so please close the issue.
