### ISSUE TITLE
If we can set the main switch of a log shows, this release can close the log information

### ISSUE THREAD

**Issue by Lnybb** [orhanobut/logger#73]
If inscribe

**Comment by CateyesLin** [comment]
+1

**Comment by orhanobut** [comment]
Hi, sorry I really didn't get the request or the issue. Could you give me more details please?

**Comment by CateyesLin** [comment]
Oh, I see there is a LogLevel.NONE can do this.

BTW the LogLevel should combine VERBOSE, DEBUG, INFO into LogLevel, and we can control log only `WARNING < level` when release.

**Comment by orhanobut** [comment]
@CateyesLin With new release, LogLevel is removed. There is another approach to control logs with [isLoggable](https://github.com/orhanobut/logger#loggable)
```java
Logger.addLogAdapter(new AndroidLogAdapter(){
  @Override public boolean isLoggable(int priority, String tag) {
    return BuildConfig.DEBUG;
  }
});
```
