### ISSUE TITLE
Can't work。V1.12

### ISSUE THREAD

**Issue by KingGGG** [orhanobut/logger#74]
![image](https://cloud.githubusercontent.com/assets/14902376/16067397/abe73e66-32ee-11e6-9371-14814477997f.png)

![image](https://cloud.githubusercontent.com/assets/14902376/16067406/cc2986ac-32ee-11e6-9f64-35217c605967.png)

I don't know...Why?Setting wrong?

**Comment by orhanobut** [comment]
This is out put of the first log. 'Log.e("KingGGG", "123321"). It seems settings are OK
