### ISSUE TITLE
when I type invalid json data to parse cause crash application 

### ISSUE THREAD

**Issue by 18039869490** [orhanobut/logger#79]
Method:  public void json(String json)

Code: e(e.getCause().getMessage() + "\n" + json);

Cause: e.getCause() get value is NULL and throw NULLPointerException

Solution: you can use e.getMessage() or e.toString(), but e.toString() is better than e.getMessage()

**Comment by orhanobut** [comment]
Which version are you using?

**Comment by 18039869490** [comment]
I using version is 1.12, You are already resolved  this problem in version 1.13。 Disturb you, I am sorry!

**Comment by orhanobut** [comment]
No worries, 👍
