### ISSUE TITLE
Logger call shown as last method call

### ISSUE THREAD

**Issue by kyhule** [orhanobut/logger#8]
Just experimenting with this library for the first time and I am seeing the Logger.d calls as on of the method calls.  It seems like form your examples that should not be the case.  Am I doing something wrong or is there a bug here?
![screen shot 2015-03-26 at 3 45 02 pm](https://cloud.githubusercontent.com/assets/2845460/6855407/36cf1480-d3ce-11e4-84b8-36597a88243a.png)

**Comment by orhanobut** [comment]
Thanks, apparently this is a bug, I'll check it out as soon as possible.

**Comment by ccunniff** [comment]
This was fixed with merge dfe2d93
