### ISSUE TITLE
the log auto be closed  in release Apk

### ISSUE THREAD

**Issue by nysin** [orhanobut/logger#82]
i use it in debug mode.when i release apk,and upload it into store,when user run the app ,the log print out or not ,how do i close the log print ,when i release app?

**Comment by orhanobut** [comment]
Have you tried LogLevel.NONE?

**Comment by enginebai** [comment]
I use the code to detect.

```java
if ((0 != (getApplicationInfo().flags &= ApplicationInfo.FLAG_DEBUGGABLE)))
	Logger.init(); // for debug, print all log
else
	Logger.init().logLevel(LogLevel.NONE); // for release, remove all log
```

**Comment by orhanobut** [comment]
LogLevel is removed with the version 2.0. In order to disable logs, following method needs to be overwriten.

```java
Logger.addLogAdapter(new AndroidLogAdapter(){
  @Override public boolean isLoggable(int priority, String tag) {
    return BuildConfig.DEBUG;
  }
});
```
