### ISSUE TITLE
 not have access permission

### ISSUE THREAD

**Issue by caiyoufei** [orhanobut/logger#85]
Original:
Logger
  .init(YOUR_TAG)                 // default PRETTYLOGGER or use just init()
  .methodCount(3)                 // default 2
  .hideThreadInfo()               // default shown
  .logLevel(LogLevel.NONE)        // default LogLevel.FULL
  .methodOffset(2)                // default 0
  .logAdapter(new AndroidLogAdapter()); //default AndroidLogAdapter
////////////////////////////////////////////////////////////////////////////////////////////
"new AndroidLogAdapter() " not have access permission
////////////////////////////////////////////////////////////////////////////////////////////
but can use like this:
"new Settings().getLogAdapter()"

**Comment by orhanobut** [comment]
As default, Logger uses AndroidLogAdapter. You don't need to set it. I guess I should use different term in the example.

**Comment by caiyoufei** [comment]
Thanks
