### ISSUE TITLE
How to implement to show all logs with this logger ?

### ISSUE THREAD

**Issue by txadf** [orhanobut/logger#86]
Using the system log can`t  show all json result if it`s to long, but use this logger,it can show all,how to implement? if using the system log, how to set android studio to show all log?

**Comment by orhanobut** [comment]
Can you elaborate your question? I didn't get it.

**Comment by van048** [comment]
@txadf You should notice that this logger logs a json line by line, not all at once. The implementation is just using a byte array to help.
