### ISSUE TITLE
Dose the tag set only once, can set in method?

### ISSUE THREAD

**Issue by microDD** [orhanobut/logger#91]
why do not offer methods like Logger.d("tag", "some info.."). So i can change the tag dynamicly。

**Comment by orhanobut** [comment]
There is an option for this: 

`Logger.t("tag").d("your message")`

**Comment by microDD** [comment]
ok,thanks.And I download the codes, and add some methods like this:
    public static void d (String tag, String message, Object... args) {
          Logger.t("tag").d("your message")
    }
