### ISSUE TITLE
some question for class Logger

### ISSUE THREAD

**Issue by Ayvytr** [orhanobut/logger#94]
if you use   Logger.e("onMeasure", widthMeasureSpec, heightMeasureSpec);
(type of widthMeasureSpec, heightMeasureSpec are int), you won't see the log for these numbers, so I suggest that, add some members in class Logger that for type of int and other types of number

**Comment by van048** [comment]
I think you should use `Logger.e("onMeasure %d %d", widthMeasureSpec, heightMeasureSpec);`.

**Comment by Ayvytr** [comment]
Thank you, you are right. I didn't know before. As a programmer, I tried programming more simply. Such as L.e("Log", 1, 2), etc. Although this is not the best, just try.

**Comment by orhanobut** [comment]
Thanks for the answer @van048  :) I'll close the issue. 

PS: @Ayvytr  Logger uses String.format under the hood therefore you need to provide arguments (%d) etc
