### ISSUE TITLE
json string  order wrong 

### ISSUE THREAD

**Issue by ihrthk** [orhanobut/logger#95]
json：
{"resultStatus":1,"errorCode":"0","data":{"inc_score":"+108","total_score":1816,"showtime":15,"type":2,"jump":{"extend":{"action":"com.stv.ucenter.action","isParse":1,"launchMode":1},"value":{"from":"com.stv.plugin.ucenter","value":{"type":3,"privilege":1}}},"jump_text":""}}

logger:
║ {
║   "resultStatus": 1,
║   "data": {
║     "showtime": 15,
║     "jump_text": "",
║     "inc_score": "+108",
║     "total_score": 1816,
║     "type": 2,
║     "jump": {
║       "extend": {
║         "launchMode": 1,
║         "action": "com.stv.ucenter.action",
║         "isParse": 1
║       },
║       "value": {
║         "from": "com.stv.plugin.ucenter",
║         "value": {
║           "privilege": 1,
║           "type": 3
║         }
║       }
║     }
║   },
║   "errorCode": "0"
║ }

**Comment by orhanobut** [comment]
I'll check if there is a possibility the maintain the order but is it really important though?
