### ISSUE TITLE
about copy  text is hardlly

### ISSUE THREAD

**Issue by zhangjiafan8652** [orhanobut/logger#98]
the log look pretty，but if iwant to copy json text ，it will copy text and border together。

**Comment by orhanobut** [comment]
@zhangjiafan8652 can you give me an example? I couldn't grasp the issue

**Comment by orhanobut** [comment]
@zhangjiafan8652 you can always try column selection. https://www.jetbrains.com/help/idea/2017.1/selecting-text-in-the-editor.html#d393106e346 although it has its own downsides

**Comment by lzjtugjc** [comment]
* I have the same problem,I want to copy json,But always copy to some useless string
* like this  ![img](https://i.imgur.com/Ouk8uLj.png)

**Comment by cs8** [comment]
![image](https://user-images.githubusercontent.com/4374690/158544594-69b19f12-e378-461e-aedd-2cebbd537f6c.png)



I want copy the json .but I dont want copy the left '|'  I do not want to use ctrl+F to replace  Can I do something setting to remove it?
