### ISSUE TITLE
logger timestamp and tab-delimited

### ISSUE THREAD

**Issue by zorro0799** [orhanobut/logger#99]
Thanks to the developer's work, my problem is that I used the adb logcat > d: / XXX. TXT redirected to a file, use logger no timestamp is very convenient, can add a timestamp?
2. Without the tab-delimited time can remove the tab-delimited

**Comment by orhanobut** [comment]
@zorro0799 I'm sorry, I didn't understand the issue clearly. Do you need timestamp in logs? Current logcat already contains one though.
Can you elaborate the second part? Thanks

**Comment by orhanobut** [comment]
Closing this issue since the issue is not clear.
